name: media_kit
description: A complete video & audio playback library for Flutter & Dart. Performant, stable, feature-proof & modular.
homepage: https://github.com/alexmercerind/media_kit
repository: https://github.com/alexmercerind/media_kit
version: 0.0.3+1
funding:
  - https://www.github.com/sponsors/alexmercerind

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  ffi: ^2.0.1
  meta: ^1.8.0
  path: ^1.8.0
  http: ^0.13.4
  uri_parser: ^2.0.2
  safe_local_storage: ^1.0.2

dev_dependencies:
  lints: ^1.0.0

ffigen:
  name: MPV
  output: bin/generated/libmpv/bindings.dart
  headers:
    entry-points:
      - headers/client.h
  dart-bool: true
