name: media_kit_test
description: A minimal application for demonstrating & testing package:media_kit
homepage: https://github.com/media-kit/media-kit
repository: https://github.com/media-kit/media-kit
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  media_kit:
    path: ../media_kit
  media_kit_video:
    path: ../media_kit_video
  media_kit_libs_video:
    path: ../libs/universal/media_kit_libs_video

  path: ^1.8.2
  file_picker: ^8.1.3
  path_provider: ^2.0.14
  http: ">=0.13.0 <2.0.0"
  universal_platform: ^1.0.0+1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
