name: video_player_media_kit
description: package:video_player support for all platforms, based on package:media_kit.
homepage: https://github.com/media-kit/media-kit
repository: https://github.com/media-kit/media-kit
version: 1.0.5
topics:
  - video
  - video-player
  - cross-platform
  - media-kit

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

  # NOTE: Bump before publishing to pub.dev
  media_kit: ^1.1.10
  media_kit_video: ^1.2.4

  universal_platform: ^1.0.0+1
  video_player_platform_interface: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

