name: media_kit_video
description: Native implementation for video playback in package:media_kit.
homepage: https://github.com/media-kit/media-kit
repository: https://github.com/media-kit/media-kit
version: 1.2.4
topics:
  - video
  - video-player
  - audio
  - audio-player
  - cross-platform

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

  # media_kit: ^1.1.10

  synchronized: ^3.1.0
  wakelock_plus: ^1.2.2
  screen_brightness: ^1.0.0
  volume_controller: ^2.0.7
  universal_platform: ^1.0.0+1
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_lints: ^3.0.2

# NOTE: Remove before publishing to pub.dev
dependency_overrides:
  media_kit:
    path: ../media_kit

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: MediaKitVideoPluginCApi
      linux:
        pluginClass: MediaKitVideoPlugin
      macos:
        pluginClass: MediaKitVideoPlugin
      ios:
        pluginClass: MediaKitVideoPlugin
      android:
        package: com.alexmercerind.media_kit_video
        pluginClass: MediaKitVideoPlugin
      web:
