name: media_kit_video
description: Native implementation for video playback in package:media_kit.
homepage: https://github.com/alexmercerind/media_kit
repository: https://github.com/alexmercerind/media_kit
version: 0.0.2
funding:
  - https://www.github.com/sponsors/alexmercerind

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.0.1
  media_kit: ^0.0.2
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: MediaKitVideoPluginCApi
      linux:
        pluginClass: MediaKitVideoPlugin
      macos:
        pluginClass: MediaKitVideoPlugin
      ios:
        pluginClass: MediaKitVideoPlugin
      android:
        package: com.alexmercerind.media_kit_video
        pluginClass: MediaKitVideoPlugin
